resolvers += Resolver.sonatypeRepo("public")

addSbtPlugin("org.scalaxb"       % "sbt-scalaxb"          % "1.7.0")
addSbtPlugin("com.typesafe.sbt"  % "sbt-native-packager"  % "1.3.1")
addSbtPlugin("com.github.gseitz" % "sbt-release"          % "1.0.6")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"        % "1.5.1")
addSbtPlugin("com.timushev.sbt"  % "sbt-updates"          % "0.3.4")
addSbtPlugin("net.virtual-void"  % "sbt-dependency-graph" % "0.9.0")
addSbtPlugin("com.typesafe.sbt"  % "sbt-git"              % "0.9.3")
addSbtPlugin("com.eed3si9n"      % "sbt-buildinfo"        % "0.8.0")
